name: markdown-auto-catalog

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: minoic/markdown-auto-catalog@v1.0.2
        with:
          content-path: 'CTF-WriteUp/folder'
          document-path: 'CTF-WriteUp/README.md'
          filter: '\(.*\).md'
        continue-on-error: true
